version: "3"
services:
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    networks:
      - monitoring
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=carDB
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  dashboard:
    image: grafana/grafana
    links:
      - influxdb 
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    networks:
      - monitoring
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
  injector:
    build: ./injector
    image: rp_injector
    links:
      - influxdb
    networks:
      - monitoring
    environment:
      - RASPILOT_IP=${RASPILOT_IP}
      - INFLUXDB_IP=${INFLUXDB_IP}

networks:
  monitoring:

volumes:
  grafana:
  influxdb:
